### ISSUE TITLE
unexpected interaction between tls and softhsm on MacOS Sonoma

### ISSUE THREAD

**Issue by kristian1108** [rustls/rustls#1638] opened 2023-11-28 20:53 UTC
**Checklist**
* [ x ] I've searched the issue tracker for similar bugs.

**Describe the bug**

In short, something in the TLS code of `reqwest` is causing a fatal interaction with the Rust SoftHSM bindings.

I filed this issue in cryptoki (https://github.com/parallaxsecond/rust-cryptoki/issues/191) as well, but this is blocking me from developing locally on my mac so hoping to get some more support.

You can see the interaction by running my reproduction code: https://github.com/kristian1108/boring-reproduce. Note this only appears to be an issue on MacOS Sonoma.

**To Reproduce**

https://github.com/kristian1108/boring-reproduce

**Applicable Version(s)**
A list of versions and platforms you've tested with.

**Expected behavior**

**Additional context**

**Comment by cpu** [comment] 2023-11-28 21:19
> I believe that means it's not using Rustls at all, and is instead defaulting to the [native-tls](https://docs.rs/native-tls/latest/native_tls/) crate:

<details>
<summary>The output of 'cargo tree' in your reproducer crate confirms this:</summary>

```
[nix-shell:/tmp/boring-reproduce]$ cargo tree
    Updating crates.io index
  Downloaded cryptoki v0.6.1
  Downloaded cryptoki-sys v0.1.7
  Downloaded 2 crates (242.3 KB) in 1.08s
boring-repro v0.1.0 (/tmp/boring-reproduce)
├── cryptoki v0.6.1
│   ├── bitflags v1.3.2
│   ├── cryptoki-sys v0.1.7
│   │   └── libloading v0.7.4
│   │       └── cfg-if v1.0.0
│   ├── libloading v0.7.4 (*)
│   ├── log v0.4.20
│   ├── paste v1.0.14 (proc-macro)
│   └── secrecy v0.8.0
│       └── zeroize v1.7.0
├── reqwest v0.11.22
│   ├── base64 v0.21.5
│   ├── bytes v1.5.0
│   ├── encoding_rs v0.8.33
│   │   └── cfg-if v1.0.0
│   ├── futures-core v0.3.29
│   ├── futures-util v0.3.29
│   │   ├── futures-core v0.3.29
│   │   ├── futures-task v0.3.29
│   │   ├── pin-project-lite v0.2.13
│   │   └── pin-utils v0.1.0
│   ├── h2 v0.3.22
│   │   ├── bytes v1.5.0
│   │   ├── fnv v1.0.7
│   │   ├── futures-core v0.3.29
│   │   ├── futures-sink v0.3.29
│   │   ├── futures-util v0.3.29 (*)
│   │   ├── http v0.2.11
│   │   │   ├── bytes v1.5.0
│   │   │   ├── fnv v1.0.7
│   │   │   └── itoa v1.0.9
│   │   ├── indexmap v2.1.0
│   │   │   ├── equivalent v1.0.1
│   │   │   └── hashbrown v0.14.2
│   │   ├── slab v0.4.9
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.1.0
│   │   ├── tokio v1.34.0
│   │   │   ├── bytes v1.5.0
│   │   │   ├── libc v0.2.150
│   │   │   ├── mio v0.8.9
│   │   │   │   └── libc v0.2.150
│   │   │   ├── num_cpus v1.16.0
│   │   │   │   └── libc v0.2.150
│   │   │   ├── parking_lot v0.12.1
│   │   │   │   ├── lock_api v0.4.11
│   │   │   │   │   └── scopeguard v1.2.0
│   │   │   │   │   [build-dependencies]
│   │   │   │   │   └── autocfg v1.1.0
│   │   │   │   └── parking_lot_core v0.9.9
│   │   │   │       ├── cfg-if v1.0.0
│   │   │   │       ├── libc v0.2.150
│   │   │   │       └── smallvec v1.11.2
│   │   │   ├── pin-project-lite v0.2.13
│   │   │   ├── signal-hook-registry v1.4.1
│   │   │   │   └── libc v0.2.150
│   │   │   ├── socket2 v0.5.5
│   │   │   │   └── libc v0.2.150
│   │   │   └── tokio-macros v2.2.0 (proc-macro)
│   │   │       ├── proc-macro2 v1.0.69
│   │   │       │   └── unicode-ident v1.0.12
│   │   │       ├── quote v1.0.33
│   │   │       │   └── proc-macro2 v1.0.69 (*)
│   │   │       └── syn v2.0.39
│   │   │           ├── proc-macro2 v1.0.69 (*)
│   │   │           ├── quote v1.0.33 (*)
│   │   │           └── unicode-ident v1.0.12
│   │   ├── tokio-util v0.7.10
│   │   │   ├── bytes v1.5.0
│   │   │   ├── futures-core v0.3.29
│   │   │   ├── futures-sink v0.3.29
│   │   │   ├── pin-project-lite v0.2.13
│   │   │   ├── tokio v1.34.0 (*)
│   │   │   └── tracing v0.1.40
│   │   │       ├── pin-project-lite v0.2.13
│   │   │       └── tracing-core v0.1.32
│   │   │           └── once_cell v1.18.0
│   │   └── tracing v0.1.40 (*)
│   ├── http v0.2.11 (*)
│   ├── http-body v0.4.5
│   │   ├── bytes v1.5.0
│   │   ├── http v0.2.11 (*)
│   │   └── pin-project-lite v0.2.13
│   ├── hyper v0.14.27
│   │   ├── bytes v1.5.0
│   │   ├── futures-channel v0.3.29
│   │   │   └── futures-core v0.3.29
│   │   ├── futures-core v0.3.29
│   │   ├── futures-util v0.3.29 (*)
│   │   ├── h2 v0.3.22 (*)
│   │   ├── http v0.2.11 (*)
│   │   ├── http-body v0.4.5 (*)
│   │   ├── httparse v1.8.0
│   │   ├── httpdate v1.0.3
│   │   ├── itoa v1.0.9
│   │   ├── pin-project-lite v0.2.13
│   │   ├── socket2 v0.4.10
│   │   │   └── libc v0.2.150
│   │   ├── tokio v1.34.0 (*)
│   │   ├── tower-service v0.3.2
│   │   ├── tracing v0.1.40 (*)
│   │   └── want v0.3.1
│   │       └── try-lock v0.2.4
│   ├── hyper-tls v0.5.0
│   │   ├── bytes v1.5.0
│   │   ├── hyper v0.14.27 (*)
│   │   ├── native-tls v0.2.11
│   │   │   ├── log v0.4.20
│   │   │   ├── openssl v0.10.59
│   │   │   │   ├── bitflags v2.4.1
│   │   │   │   ├── cfg-if v1.0.0
│   │   │   │   ├── foreign-types v0.3.2
│   │   │   │   │   └── foreign-types-shared v0.1.1
│   │   │   │   ├── libc v0.2.150
│   │   │   │   ├── once_cell v1.18.0
│   │   │   │   ├── openssl-macros v0.1.1 (proc-macro)
│   │   │   │   │   ├── proc-macro2 v1.0.69 (*)
│   │   │   │   │   ├── quote v1.0.33 (*)
│   │   │   │   │   └── syn v2.0.39 (*)
│   │   │   │   └── openssl-sys v0.9.95
│   │   │   │       └── libc v0.2.150
│   │   │   │       [build-dependencies]
│   │   │   │       ├── cc v1.0.83
│   │   │   │       │   └── libc v0.2.150
│   │   │   │       ├── pkg-config v0.3.27
│   │   │   │       └── vcpkg v0.2.15
│   │   │   ├── openssl-probe v0.1.5
│   │   │   └── openssl-sys v0.9.95 (*)
│   │   ├── tokio v1.34.0 (*)
│   │   └── tokio-native-tls v0.3.1
│   │       ├── native-tls v0.2.11 (*)
│   │       └── tokio v1.34.0 (*)
│   ├── ipnet v2.9.0
│   ├── log v0.4.20
│   ├── mime v0.3.17
│   ├── native-tls v0.2.11 (*)
│   ├── once_cell v1.18.0
│   ├── percent-encoding v2.3.0
│   ├── pin-project-lite v0.2.13
│   ├── serde v1.0.193
│   ├── serde_json v1.0.108
│   │   ├── itoa v1.0.9
│   │   ├── ryu v1.0.15
│   │   └── serde v1.0.193
│   ├── serde_urlencoded v0.7.1
│   │   ├── form_urlencoded v1.2.0
│   │   │   └── percent-encoding v2.3.0
│   │   ├── itoa v1.0.9
│   │   ├── ryu v1.0.15
│   │   └── serde v1.0.193
│   ├── tokio v1.34.0 (*)
│   ├── tokio-native-tls v0.3.1 (*)
│   ├── tower-service v0.3.2
│   └── url v2.4.1
│       ├── form_urlencoded v1.2.0 (*)
│       ├── idna v0.4.0
│       │   ├── unicode-bidi v0.3.13
│       │   └── unicode-normalization v0.1.22
│       │       └── tinyvec v1.6.0
│       │           └── tinyvec_macros v0.1.1
│       └── percent-encoding v2.3.0
├── secrecy v0.8.0 (*)
└── tokio v1.34.0 (*)
```
</details>

Unfortunately that means I think we're unable to help you here so I'm going to close this issue. If the diagnoses changes and it looks like Rustls is implicated in some way we can debug further.

Best of luck,

**Closed by cpu** 2023-11-28 21:19 UTC

**Comment by ctz** [comment] 2023-11-28 21:38
If I were you, I would be looking carefully at having boringssl and openssl (or other combinations of other forks) in the same process space. I really doubt that can ever work.

I don't think the repro is now using rustls -- you have enabled the feature, but also need to use the APIs it enables.

**Comment by ctz** [comment] 2023-11-28 22:14
> I don't have boringssl installed on my machine.

I'm only going by the fact that the assertion that fails mentions this. If you don't have this file and it is not available from Apple, I think you will need to ask Apple for support. Failing that, you could ask the homebrew project for help with their build of softhsm.

I'm not a macos user, so it's difficult to make helpful suggestions. If this were linux, the steps I'd suggest would be: capture a core dump when the assertion fails, load that into a debugger like GDB, and look for evidence of multiple, conflicting definitions of openssl symbols, especially those at addresses referenced in the previous instructions leading up to the assertion failure. Another route would be looking at the link-time dependencies of your `target/debug/boring-repro` and `/opt/homebrew/Cellar/softhsm/2.6.1/lib/softhsm/libsofthsm2.so` binaries (eg, using `ldd`).
