### ISSUE TITLE
IP in client hello SNI will raise InvalidServerName on server side

### ISSUE THREAD

**Issue by viecks** [rustls/rustls#1310] opened 2023-06-08 12:09 UTC
In rustls 0.21.1, Connect to IP works well，but when i use go-grpc client to dial a hyper service with rust-tls 0.21.1 by ip (then the SNI in ClientHello will be the IP), the server will raise a handshake error like "received corrupt message of type InvalidServerName".

After i override ServerName (SNI) as a domain name on client side, the request is works.

**Comment by thalesfragoso** [comment] 2023-06-08 13:15
This is a client bug, the SNI extension doesn't allow IP addresses.

**Comment by cpu** [comment] 2023-06-08 13:32
This also came up in https://github.com/rustls/rustls/issues/1127 

There are some options on the table for adjustments on the Rustls side but as @thalesfragoso notes this is a client bug so the ideal outcome would be to fix the bug there so it can be squashed in one place instead of in many separate server implementations.

**Comment by cpu** [comment] 2023-06-12 20:01
> It would be useful to have a packet capture or, better yet, a minimal reproducible example. I'm curious what Go/g-rpc send in the ServerName extension in this case. 

@viecks Do you think you could provide a minimal reproducer? It would be helpful for deciding whether this is something that could be reported to the upstream project.

**Comment by ctz** [comment] 2023-06-13 10:48
I'm assuming go-grpc uses crypto.tls in the standard library. It seems that does the right thing in avoiding sending invalid SNI extensions: https://github.com/golang/go/blob/master/src/crypto/tls/handshake_client.go#L1095-L1113

**Comment by cpu** [comment] 2023-07-04 17:26
This appears to be a client-side bug and I don't believe we have enough information to report the problem to an upstream project. I'm going to close this for now and we can revisit if more information becomes available.

**Closed by cpu** 2023-07-04 17:26 UTC

**Comment by sludin** [comment] 2023-07-09 22:48
I am not arguing that this is not a client bug, but it looks like there is a desire for examples. curl sends the ip address in the SNI extension by default.  Of course this can be suppressed with -k or worked around with --resolve, but it would be great if there was a way to get rustls to accept it, similar to how the ResolveServerCert trait was added to make cert matching more flexible. This is probably most relevant in development.

Capture generated with: 
`curl https://127.0.0.1:8443`

[ip_in_sni.pcapng.zip](https://github.com/rustls/rustls/files/11996458/ip_in_sni.pcapng.zip)

**Comment by sludin** [comment] 2023-07-09 22:59
And... the more I think about the curl case the more I think my ask is not well thought out.  Without -k I would just get an error on the curl side anyway.  Regardless the example may still be useful.

**Comment by cbiffle** [comment] 2024-01-20 18:51
I realize this bug is long-closed, and I'm happy to open another one if you'd prefer, but -- this is coming up in search results for `rustls InvalidServerName`. If I wanted to alter this behavior of rustls, because I'm specifically writing an isolated honeypot server to intercept what I suspect to be attacks on my webserver, is there a component equivalent to the client-side `ServerCertVerifier` that I could swap out for my own implementation?

**Comment by ctz** [comment] 2024-01-20 19:03
There's not an extension point that allows altering this. I would suggest you fork/vendor rustls and do something like ignoring syntactically invalid SNI entries.
