### ISSUE TITLE
Forced inclusion of aws-lc-rs causes linker errors

### ISSUE THREAD

**Issue by Diggsey** [rustls/rustls#2010] opened 2024-06-18 12:50 UTC
With `aws-lc-rs` enabled by a default feature and therefore impossible to disable without forking all intermediate crates, there is no way to remove it form the crate graph.

Including it causes linker errors due to erroneously exported symbols:

https://github.com/aws/aws-lc-rs/issues/446

This breaks all downstream crates of rustls which use boring-sys.

**Comment by ctz** [comment] 2024-06-18 13:16
What action are you expecting rustls to do here?

**Comment by Diggsey** [comment] 2024-06-18 13:23
Remove `aws-lc-rs` as a default feature until it's no longer broken.

**Comment by ctz** [comment] 2024-06-18 13:45
I don't think that is proportionate or reasonable.

Especially as the issue is equally boring-sys's problem (it is not a bona-fide -sys crate -- it builds and includes the boringssl code itself). It takes two crates to fail to prefix all their symbols for this issue to occur (see, eg, https://github.com/cloudflare/boring/issues/197 ).

Going to close this.

**Closed by ctz** 2024-06-18 13:45 UTC

**Comment by Diggsey** [comment] 2024-06-18 13:54
Since rustls refuses to provide any workaround to breaking the entire world I've had to fork the crate and remove the trash that is aws-lc: https://github.com/Diggsey/rustls.git
