### ISSUE TITLE
`rustls::Stream` EOF handling may not be appropriate

### ISSUE THREAD

**Issue by quininer** [rustls/rustls#1188] opened 2023-01-31 01:49 UTC
> rustls Stream cannot distinguish between a normal close notify and an unexpected tcp eof, which allows truncation attack, which I suspect is not expected.

see https://github.com/tokio-rs/tls/pull/128

**Comment by djc** [comment] 2023-01-31 08:04
I've been wondering whether we should just remove `Stream`? At least for me it sort of feels like an afterthought since it seems to me that the audience is pretty narrow -- most people will be using something like tokio-rustls and for the majority of the remaining users, I feel like the `ConnectionCommon` API (including `complete_io()`) is probably a decent option.

**Comment by ctz** [comment] 2023-02-04 10:25
I think `Stream` should be tracking the behaviour introduced in #790; but it's unclear why that didn't happen. Needs some additional testing.

**Comment by djc** [comment] 2023-03-17 09:51
@cpu maybe this is something you can look into? Would be good to get this fixed.

**Comment by cpu** [comment] 2023-03-17 12:51
> @cpu maybe this is something you can look into?

Sure, I'll take a look.

**Comment by cpu** [comment] 2023-03-17 17:03
I was able to use the reproducers from https://github.com/tokio-rs/tls/pull/128 to make some progress here. Many thanks for including those! For convenience I created a Cargo workspace with both and all the required deps/feature flags to easily run locally: https://github.com/cpu/stream-eof-mrp

> I think Stream should be tracking the behaviour introduced in https://github.com/rustls/rustls/pull/790; but it's unclear why that didn't happen.

I think the crux of the issue is in this logic in `Stream.read` where `complete_io` and `process_new_packets` are called, trying to prematurely signal EOF: https://github.com/rustls/rustls/blob/da6aeb76858699293361caa4093235753d895181/rustls/src/stream.rs#L55-L73

As written, when the peer closes the connection prematurely this logic ends up returning `Ok(0)` (on L66) _before_ calling `conn.reader().read(buf)` (on L73). The `Reader.read` func is where #790 introduced logic to change how the EOF is handled based on whether the peer sent `close_notify` and so the `Stream.read` effectively side-steps the fix from #790.

I was able to fix the reproducer by updating the `Stream.read` logic to check the `io_state.peer_has_closed()` result, using that to help inform whether to prematurely signal EOF with `Ok(0)` (iff the peer has closed correctly) or `Err(io:ErrorKind::UnexpectedEof)` (iff the peer hasn't closed correctly). PTAL at  https://github.com/cpu/rustls/commit/1acb165b718ce44fab9712173b4dfdbdeda116fc

I'm not sure if we'd prefer to fix this in `Stream` (as I have in the commit linked above), or if this should be handled elsewhere (maybe in `complete_io`? :thinking:).

**Comment by djc** [comment] 2023-03-21 21:55
Ideally we'd fix this in a way that we don't need need to duplicate the logic from `Reader::read()`. It seems suspicious to me that `complete_io()` is yielding `Ok(0)` here when in fact we it should be yielding `UnexpectedEof`?

**Comment by cpu** [comment] 2023-03-21 21:59
>  It seems suspicious to me that complete_io() is yielding Ok(0) here when in fact we it should be yielding UnexpectedEof?

I forgot to update this ticket after I did a little bit more digging at trying to move my fix up into `complete_io`. The `Ok(0)` yield comes from the `match` at the end of the function that was added by @quininer in https://github.com/rustls/rustls/commit/e05543f0b50a3c311e78cb5893e911fff5d86014 to fix an infinite loop. I was looking at this again close to the end of the day and was having a hard time working backwards from the code to the intent w.r.t. the possible IO states. I think we're both coming to the same conclusion that the match could be buggy.

**Comment by cpu** [comment] 2023-03-21 22:00
I would think we want the `_` match arms to not take precedence over `eof == true` but maybe the intent is to return the partial data with the hope of surfacing the EOF subsequently (?)

**Comment by djc** [comment] 2023-03-22 08:09
In general if data was returned we need to forward that to the caller. But if we encountered some kind of error we should make sure to also yield the error in the next invocation.

**Comment by cpu** [comment] 2023-04-17 15:14
> I'll look at pursuing this after the release tag is cut.

I'm still interested in pursuing a fix for this bug. I have some thoughts but want https://github.com/rustls/rustls/pull/1273 to make progress first since I believe in both cases `complete_io` is at the crux of the issue.

**Closed** 2023-05-23 13:08 UTC
