### ISSUE TITLE
How to use it in multithreaded scenarios?

### ISSUE THREAD

**Issue by ryanrain2016** [rustls/rustls#842] opened 2021-10-25 07:21 UTC
I try to use rustls::Stream in two thread to handle read and write in two different threads.  Is there any method like native `TcpStream::try_clone` here to clone the stream? I really appreciate if some examples provided.

**Comment by bdaehlie** [comment] 2022-11-02 14:37
Duplicate of #288.

**Closed by bdaehlie** 2022-11-02 14:37 UTC
