### ISSUE TITLE
from_subject_spki_name_constraints on rustls 0.23.9

### ISSUE THREAD

**Issue by lorenzo-pirchio** [rustls/rustls#1997] opened 2024-06-10 14:26 UTC
Can anyone help me to write the following code using rustls 0.23.9, because I have problems with from_subject_spki_name_contraints.
I have been trying to rewrite this code for 2 days but I can't find the solution.

```rust
let mut root_store = RootCertStore::empty();
    //TLS_SERVER_ROOTS rappresenta un elenco predefinito di certificati radice forniti dalla libreria webpki_roots
    //Add certificates to 
    root_store.add(webpki_roots::TLS_SERVER_ROOTS.iter().map(|ta| {
        TrustAnchor::from_subject_spki_name_constraints(
           ta.subject,
            ta.spki,
            ta.name_constraints,
        )
    }));
```

**Comment by ctz** [comment] 2024-06-10 14:30
`from_subject_spki_name_constraints` does not exist nowadays. Suggest you follow the example code: https://github.com/rustls/rustls/blob/main/examples/src/bin/simpleclient.rs#L18-L20

**Comment by lorenzo-pirchio** [comment] 2024-06-10 14:39
I have errors:

C:\Crates_mod\xmpp-rs\tokio-xmpp\src\starttls\mod.rs:141:47
    |
141 |         roots: webpki_roots::TLS_SERVER_ROOTS.into(),
    |                                               ^^^^ the trait `std::convert::From<&[webpki_roots::TrustAnchor<'_>]>` is not implemented for `Vec<tokio_rustls::rustls::pki_types::TrustAnchor<'_>>`, which is required by `&[webpki_roots::TrustAnchor<'_>]: Into<_>`
    |
    = help: the following other types implement trait `std::convert::From<T>`:
              <Vec<u8> as std::convert::From<bytes::Bytes>>
              <Vec<u8> as std::convert::From<BytesMut>>
              <Vec<u8> as std::convert::From<CString>>
              <Vec<u8> as std::convert::From<String>>
              <Vec<u8> as std::convert::From<&str>>
              <Vec<T> as std::convert::From<[T; N]>>
              <Vec<T, A> as std::convert::From<Box<[T], A>>>
              <Vec<T, A> as std::convert::From<BinaryHeap<T, A>>>
            and 6 others
    = note: required for `&[webpki_roots::TrustAnchor<'_>]` to implement `Into<Vec<tokio_rustls::rustls::pki_types::TrustAnchor<'_>>>`

**Comment by cpu** [comment] 2024-06-10 14:41
@lorenzo-pirchio What version of `webpki-roots` are you using? Can you post a more complete reproduction?

**Comment by lorenzo-pirchio** [comment] 2024-06-10 14:51
I'm tring to use tokio-xmpp using rustls 0.23.9 but I've problems with the method I wrote before.
I'm using webpki 0.25.4.

This was the original method:
#[cfg(all(feature = "tls-rust", not(feature = "tls-native")))]
async fn get_tls_stream<S: AsyncRead + AsyncWrite + Unpin>(xmpp_stream: XMPPStream<S>) -> Result<TlsStream<S>, Error> {
    //XMPP domain extracted from the jid

    let domain = xmpp_stream.jid.domain().to_string();
    //server name extracted from jid
    let domain = ServerName::try_from(domain.as_str())?;
    let stream = xmpp_stream.into_inner();
    //Used to save root certificates during connection
    let mut root_store = RootCertStore::empty();
    //Add certificates to 
    root_store.add(webpki_roots::TLS_SERVER_ROOTS.iter().map(|ta| {
        TrustAnchor::from_subject_spki_name_constraints(
            ta.subject,
            ta.spki,
            ta.name_constraints,
       )
    }));
    //Client configuration
     let config = ClientConfig::builder()
        .with_root_certificates(root_store) // Aggiungi il RootCertStore con i trust anchors
        .with_no_client_auth(); // Disabilita l'autenticazione del client
    let tls_stream = TlsConnector::from(Arc::new(config))
        .connect(domain, stream)
        .await
        .map_err(|e| Error::from(crate::Error::Io(e)))?;
    Ok(tls_stream)

Then I changed to this:
#[cfg(all(feature = "tls-rust", not(feature = "tls-native")))]
async fn get_tls_stream<S: AsyncRead + AsyncWrite + Unpin>(xmpp_stream: XMPPStream<S>) -> Result<TlsStream<S>, Error> {
    //XMPP domain extracted from the jid

    let domain = xmpp_stream.jid.domain().to_string();
    //server name extracted from jid
    let domain = ServerName::try_from(domain.as_str())?;
    let stream = xmpp_stream.into_inner();
    //Used to save root certificates during connection
    let root_store = RootCertStore {
        roots: webpki_roots::TLS_SERVER_ROOTS.into(),
    };
    //Client configuration
     let config = ClientConfig::builder()
        .with_root_certificates(root_store) // Aggiungi il RootCertStore con i trust anchors
        .with_no_client_auth(); // Disabilita l'autenticazione del client
    let tls_stream = TlsConnector::from(Arc::new(config))
        .connect(domain, stream)
        .await
        .map_err(|e| Error::from(crate::Error::Io(e)))?;
    Ok(tls_stream)
}



    
    
   But I get the error I wrote before.

**Comment by cpu** [comment] 2024-06-10 14:55
> I'm tring to use tokio-xmpp using rustls 0.23.9 but I've problems with the method I wrote before.

It looks to me like `tokio-xmpp` is using [`tokio-rustls` 0.24](https://gitlab.com/xmpp-rs/xmpp-rs/-/blob/2097b9685f31ad59384db1ee2d21e2da899c1444/tokio-xmpp/Cargo.toml#L35). That release is only compatible with [rustls 0.21](https://github.com/rustls/tokio-rustls/blob/7ea7a17831691e8b0a9cfae3132d2d2f0f64221c/tokio-rustls/Cargo.toml#L17).

I don't believe you can use Rustls 0.23.x with this dependency until it has been updated to use a newer `tokio-rustls` release.

**Comment by lorenzo-pirchio** [comment] 2024-06-10 14:59
I changed tokio-xmpp depencies updating tokio-rustls to 0.26.0

**Comment by cpu** [comment] 2024-06-12 18:32
I'm going to close this issue since I think we've root caused the issue: using an incompatible version of rustls w/ tokio-rustls.

If you run into further trouble feel free to open a new issue (here, or with [tokio-rustls](https://github.com/rustls/tokio-rustls) as appropriate). Thanks!

**Closed by cpu** 2024-06-12 18:32 UTC
