### ISSUE TITLE
Connection reset by peer error when setting a client certificate

### ISSUE THREAD

**Issue by kbgoro** [rustls/rustls#1122] opened 2022-11-01 21:27 UTC
When I call the set_single_client_cert method in rustls, and send a request to an endpoint that accepts an X509 client certificate using the surf http client, I get back a Connection reset by peer(os error 104). I'm able to successfully call the endpoint from postman and native openssl probably because of tls handshake renegotiation.  I've seen a few related issues here and I know there are no plans for rustls to renegotiation in the future, but my question is what are the alternatives are for using a client certificate with rustls?  The alternative could be to require client authentication or strong cipher suites during the initial negotiation but I was hoping for some concrete examples.  Thanks

**Comment by djc** [comment] 2022-11-01 21:43
It's not really clear from your description what you're actually trying to do. Can you post a code sample?

Also note that surf appears to be stuck at rustls 0.18, which is pretty ancient at this point (I don't know if modern rustls would give you better results, but even if we did fix something we would be unlikely to release another 0.18 version).

**Comment by kbgoro** [comment] 2022-11-01 22:05
let mut tls_config = ClientConfig::new();

        // Populate the trust anchors in the root store. `ClientConfig` starts with a completely empty set of trusted roots,
        // so validate the assumption at runtime
        assert!(tls_config.root_store.is_empty());


        // Copy each of the provided trust anchors into the new
        // cert store
        for root in &self.roots {
            tls_config.root_store.add(root).unwrap();
        }


if client_cert_required {
            let key_der = secrets::fetch("id_rsa").unwrap_or(None).unwrap();   // this will fetch the private key from store
            let decoded_key_der = base64::decode(key_der).unwrap_or_default();   //decode base64 private key
            let cert_chain = secrets::fetch("signed_cert").unwrap_or(None).unwrap().into_bytes();  //fetches certificate from store
            let cert = rustls::Certificate(cert_chain);
            let key = PrivateKey::from(rustls::PrivateKey(decoded_key_der));
            let mut cert_vec: Vec<Certificate> = Vec::new();
            cert_vec.push(cert);
            match tls_config.set_single_client_cert(cert_vec, key) {
                Ok(_) => (),
                Err(e) => warn!("Could not set root certificate because of {}", e),
            };

**Comment by kbgoro** [comment] 2022-11-01 22:10
I'm basically trying to set the client certificate  as part of the tls config, but connection keeps getting dropped.

**Comment by djc** [comment] 2022-11-03 14:49
So it works with the same key/certificate with openssl? And it works if you disable client authentication?

**Comment by kbgoro** [comment] 2022-11-03 16:31
@djc    yep it does. we're able to see the request sent on our service. the problem is with using rustls is that the connection gets closed.   yeah on openssl, i don't even have to send a client certificate and I'll get an expected server error of "client certificate not found", where if I call the endpoint with or without client cert using rustls, I get a connection reset by peer error.   

also if I do something like on the reqwest http client:

let client = reqwest::Client::builder().use_native_tls().build().unwrap();  it will work too.  

in addition, if i specify native_tls on the surf client it also works.  But in my case, I'd to use rustls for the cert pinning, but can't because of the connection reset by peer error.

**Comment by djc** [comment] 2022-11-04 20:23
So, I don't really want to spend more time debugging this until you have a reproducer for this working with rustls 0.20 -- don't want to spend time only to find out that this is due to an issue that has long since been solved. I suggest using some other HTTP client than surf, since it doesn't seem like surf is getting much (if any) maintenance.

**Comment by cpu** [comment] 2023-03-31 15:57
@kbgoro I'm going to close this issue for now but if you can provide reproducing code using the latest rustls release it would make debugging much easier and we could re-open for further discussion. Thanks!

**Closed by cpu** 2023-03-31 15:57 UTC
