### ISSUE TITLE
Is KeyLogFile broken?

### ISSUE THREAD

**Issue by daladim** [rustls/rustls#875] opened 2021-12-11 10:04 UTC
I'm trying to dump TLS secrets, so that I can inspect traffic using Wireshark.

The [only example I have found online](https://users.rust-lang.org/t/support-for-sslkeylogfile-in-https-client-from-reqwest/47616/3) seems outdated.
I have tried the following, with the latest reqwest version, but this does not work as expected.

<details><summary>Cargo.toml</summary>

```
[package]
...
[dependencies]
reqwest = { version = "0.11", features = ["rustls-tls", "blocking"] }
rustls = "0.20"
webpki-roots = "0.22"
```

</details>

<details>
  <summary>main.rs</summary>
  
```rust
use std::sync::Arc;

use reqwest::blocking::Client;
use rustls::{RootCertStore, OwnedTrustAnchor};

fn main() {
    let body = make_client()
        .get("https://www.rust-lang.org")
        .send()
        .unwrap()
        .text().unwrap();

    println!("body = {:?}", body);
}


pub fn make_client() -> Client {
    let mut root_store = RootCertStore::empty();
    root_store.add_server_trust_anchors(
        webpki_roots::TLS_SERVER_ROOTS
            .0
            .iter()
            .map(|ta| {
                OwnedTrustAnchor::from_subject_spki_name_constraints(
                    ta.subject,
                    ta.spki,
                    ta.name_constraints,
                )
            }),
    );

    let mut tls = rustls::ClientConfig::builder()
        .with_safe_defaults()
        .with_root_certificates(root_store)
        .with_no_client_auth();

    tls.alpn_protocols = vec!["h2".into(), "http/1.1".into()];
    if std::env::var("SSLKEYLOGFILE").is_err() {
        println!("SSL key logging is enabled but SSLKEYLOGFILE is not set. No key will be logged");
    }
    tls.key_log = Arc::new(rustls::KeyLogFile::new());

    Client::builder()
        .use_preconfigured_tls(tls)
        .use_rustls_tls()
        .build()
        .unwrap()
}
```
</details>

Then (I'm on Windows) on a command prompt:
```
C:\ > set SSLKEYLOGFILE=C:\Users\Public\keys.dat
C:\ > cargo run 
```

## Expected result

`C:\Users\Public\keys.dat` gets populated

## Actual result

`C:\Users\Public\keys.dat` gets created, but stays empty

Is this feature broken, or am I using it in a wrong way?
Also, could you make it more convenient to use it? e.g. with a convenience function in `impl ClientConfig` so that it fits in one line?

I _think_ this is rustls-related, even though the minimal example also uses `reqwest` and `webpki-roots`, in case you think I have posted in the wrong project, please tell me.
Thanks :-)

**Comment by djc** [comment] 2021-12-11 11:03
I don't see anything obviously wrong with your code, so I agree that this is surprising. Is the request getting executed?

**Comment by djc** [comment] 2021-12-11 11:04
As for convenience, see some recent discussion in #868.

**Comment by daladim** [comment] 2021-12-11 16:50
Thanks for the info, I searched the issues about my problem, but did not think about searching the pull requests.

Using the branch from this pull request, my `C:\Users\Public` gets populated... That's strange. I think I'll investigate a bit more in a few days (when I have time to do so :-/ ) (but maybe you'll be quicker than I am to understand what goes wrong).

My reproducer above actually performs the request, and correctly displays the response.

**Comment by djc** [comment] 2021-12-13 09:57
@daladim what documentation did you look at specifically when trying to figure out how to make this happen?

So the symptom of writing the file but not getting any data in there seems to be similar to what #871 is trying to fix. This could point to the fact that the process rustls is a part of is not "seeing" the environment variable. I also suspect this functionality may not have been used on Windows much.

I'd probably recommend just cloning rustls, changing your sample code to depend on your local clone via a `path` dependency and then sprinkling some `println!()`/`dbg!()` calls in [rustls/src/keylog.rs](https://github.com/rustls/rustls/blob/main/rustls/src/keylog.rs).

**Comment by cpu** [comment] 2023-10-16 17:19
Closing based on missing reproduction info and no reply from the OP back in march.

**Closed by cpu** 2023-10-16 17:19 UTC
