### ISSUE TITLE
invalid peer certificate: UnsupportedCertVersion

### ISSUE THREAD

**Issue by SinemBilge** [rustls/rustls#1298] opened 2023-05-17 14:47 UTC
Hello :)
Hope you are all doing well. For my thesis I am trying to implement TLS 1.3 on top of my client. Unfortunately I am really having troubles with that. I am really new to this topic and I wanted to use rustles native certs to achieve my aim. I attached my GitHub repository and the error that I am receiving to this email. I also attached an image of how my TLS file looks like on my desktop.I would be really glad if you could help me to fix my code if that's the problem or help me to change the certificates to solve my problem. Thanks 

I think that the problem might be because of:
MQTT server may have certs in an old format that webpki does not accept.

Also someone commented on my issue by saying:
The code I am seeing just loads the native certs, where do you believe
to load the cert that you generated? 

However I dont know how to interpret this as I believe that I dont need to generate other client keys in the situation where I use rustls native certs.

[tls 1.3 .txt](https://github.com/rustls/rustls/files/11499398/tls.1.3.txt)

https://github.com/SinemBilge/MQTT-TLS-1.3

<img width="743" alt="Ekran Resmi 2023-05-17 16 43 25" src="https://github.com/rustls/rustls/assets/106627414/c8fe610f-6800-47ae-ba69-c4b39932cb59">

**Comment by cpu** [comment] 2023-05-17 15:01
Hi @SinemBilge :wave: Thanks for opening an issue.

> I think that the problem might be because of:
> MQTT server may have certs in an old format that webpki does not accept.

You've correctly identified the problem. The `UnsupportedCertVersion` error you're seeing is from webpki trying to load a certificate that specifies a version other than version 3. Rustls and [webpki only supports x509 version 3 certificates](https://github.com/rustls/webpki/blob/6a388acd5e2282e9f36e4532caac8ba5c79325ba/src/cert.rs#L123-L139).

> https://github.com/SinemBilge/MQTT-TLS-1.3

If you have `openssl` installed you can see that the [`test.mosquitto.org.crt`](https://github.com/SinemBilge/MQTT-TLS-1.3/blob/5b6b112f5ee21dfb789a055c4cc0880bdd84b525/test.mosquitto.org.crt) certificate in your repository has the wrong version like so:

```
$> openssl x509 -in test.mosquitto.org.crt -noout -text | grep "Version"
        Version: 1 (0x0)
```

A supported certificate would have "Version: 3 (0x2)".

Can you speak to how that certificate was created? I notice if I connect to the "real" `test.mosquitto.org` server it uses a valid x509 v3 certificate issued by Let's Encrypt.

Changing the generation of your test certificate to fix the version number would be the best way to resolve this problem. If you share some details on how you went about creating it we might be able to suggest a concrete fix.

**Comment by cpu** [comment] 2023-05-17 15:08
> Can you speak to how that certificate was created? I notice if I connect to the "real" test.mosquitto.org server it uses a valid x509 v3 certificate issued by Let's Encrypt.

Oh! This was my mistake. I tested on port 443 but I see your code is using port 8883. When I connect to that port I do see a version 1 certificate.

I'm guessing that means the certificate was created outside of your control by the Mosquitto maintainers. Unfortunately that will make the problem hard to fix without their involvement.

Rustls and Webpki are focused on (as the name suggests) the Web PKI. In that PKI there are rules that prevent the use of anything but version 3 certificates. For that reason I suspect we wouldn't want to relax the check on our end to support this legacy certificate.

**Comment by djc** [comment] 2023-05-17 15:11
See also previous discussion in https://github.com/rustls/webpki/issues/29.

**Comment by SinemBilge** [comment] 2023-05-17 15:37
Can you give me some suggestions about what should I do right now? Based on what I understood from the commands,  I tried generating a new certificate as an extension to test.mosquitto.cert certificate I guess. At least this is what I tried to do.  I dont know how to use this certificate with my client code nor how to put it as an extension to my test.mosquitto.cert. my 

"(base) sinembilgeguler@Sinem-Macbook-Pro mqtt-client-tls 2 % openssl x509 -in new_certificate.crt -noout -text | grep "Version" 

        Version: 3 (0x2)
(base) sinembilgeguler@Sinem-Macbook-Pro mqtt-client-tls 2 % "

<img width="711" alt="Ekran Resmi 2023-05-17 17 30 08" src="https://github.com/rustls/rustls/assets/106627414/7b279d6d-4930-41f1-8c5a-6d1755d754bd">


[new problem.txt](https://github.com/rustls/rustls/files/11500061/new.problem.txt)


Before doing this, I also changed my port to 443 to see if my problem can get solved. I received the following error.
Notification = Err(NotConnAck(PubAck(PubAck { pkid: 21584 })))

**Comment by SinemBilge** [comment] 2023-05-17 15:47
Do you think chaining the port number from 1883 to 443 would solve the problem? Because I remember that you said you could make the code run with port 443? Am I wrong? However, I am receiving this error. 
Notification = Err(NotConnAck(PubAck(PubAck { pkid: 21584 }))).  What can I do?

**Comment by cpu** [comment] 2023-05-17 15:50
> Do you think chaining the port number from 1883 to 443 would solve the problem?

No, I think the problem with that approach is that the server on 443 is speaking HTTP(S) and your code is trying to speak to an MQTT server (like the one running on `:8883`). 

You'd be changing from a certificate validation error to a protocol support error.

>  However, I am receiving this error.
Notification = Err(NotConnAck(PubAck(PubAck { pkid: 21584 }))).

I'm not familiar with MQTT but I suspect this error is indicating what I'm mentioning above. You're trying to speak MQTT to a web server instead of a MQTT server.

**Comment by cpu** [comment] 2023-05-17 15:58
One action you could take immediately is to stand up your own test MQTT server, and configure it with a valid certificate. You could use that server instead of  `test.mosquitto.org:8883`.

For certificate generation I recommend using [Minica](https://github.com/jsha/minica) - it is easy to use and will generate a standards compliant certificate.

I'm afraid I can't provide any advice on how to configure your own MQTT server but hopefully there are resources available to consult for that task.

**Comment by SinemBilge** [comment] 2023-05-17 20:49
Hello, I have one more last question. I wonder why I cant use rustls tlsmioserver with my client code. If the error is from my side, could you please provide me the specific command that would make them communicate?

**Comment by cpu** [comment] 2023-05-18 13:33
Hi @SinemBilge,

>  I wonder why I cant use rustls tlsmioserver with my client code. If the error is from my side, could you please provide me the specific command that would make them communicate?

Could you share how you're running `tlsserver-mio` example program and the error you get when connecting to it? The repo you linked earlier only has the client program.

I suspect the problem is similar to changing your client to connect to `:443` of `test.mosquitto.org`. The `tlsserver-mio` binary can act as an echo server, or can respond with an HTTP response, but it doesn't know how to act as a MQTT server. If you use an MQTT client to connect to it, there will likely be errors.

**Comment by cpu** [comment] 2023-05-18 13:40
>  If the error is from my side,

Also just to clarify: the error isn't on your side. The error is with the certificate used by `test.mosquitto.org` not being compatible with `webpki`/`rustls`.

**Comment by cpu** [comment] 2023-07-04 17:29
I think there's no additional action to take on our side at this time, if we decide to relax the version requirement it would need to be discussed on the [webpki](https://github.com/rustls/webpki) repository. I'm going to close this issue and would encourage affected users to follow up with the mosquitto test server maintainers in https://github.com/eclipse/mosquitto/issues/2815

**Closed by cpu** 2023-07-04 17:29 UTC
