### ISSUE TITLE
rustls client flagged as bot by Cloudflare

### ISSUE THREAD

**Issue by darind** [rustls/rustls#1501] opened 2023-09-29 11:58 UTC
I am using rustls 0.21.7 on MacOS 13.5.2 to make a TLS request to `chat.openai.com:443`:

```
use std::io::{Read, Write};
use std::{sync::Arc, net::TcpStream};
use rustls::{Certificate, RootCertStore, ClientConfig, Stream, ClientConnection};

fn main() {
    let mut root_store = RootCertStore::empty();
    for cert in rustls_native_certs::load_native_certs().expect("could not load platform certs") {
        root_store
            .add(&Certificate(cert.0))
            .unwrap();
    }

    let mut config = ClientConfig::builder()
        .with_safe_defaults()
        .with_root_certificates(root_store)
        .with_no_client_auth();

    config.alpn_protocols.push("http/1.1".as_bytes().to_vec());

    let mut conn = ClientConnection::new(
        Arc::new(config),
        "chat.openai.com".try_into().unwrap()
    ).unwrap();

    let mut sock = TcpStream::connect("chat.openai.com:443").unwrap();
    let mut tls = Stream::new(&mut conn, & mut sock);

    tls.write("GET / HTTP/1.1\r\nHost: chat.openai.com\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36\r\nConnection: close\r\n\r\n".as_bytes()).unwrap();

    let mut buf = vec![0; 2048];
    let len = tls.read(&mut buf).unwrap();
    std::io::stdout().write_all(&buf[..len]).unwrap();
}
```

This returns `HTTP/1.1 403 Forbidden`.

I suspect that the JA3 fingerprint that rustls is generating is not matching with the one generated by popular web browsers and Cloudflare bot protection is detecting that the ClientHello is not coming from a whitelisted source.

Is it possible to control the list of tls extensions and cipher suites sent by a rustls client?

**Comment by djc** [comment] 2023-09-29 12:04
I think this is a duplicate of https://github.com/rustls/rustls/issues/1421. Have you done some testing to ascertain that the TLS-level fingerprinting is what is causing the issues here? (Like running the same minimal test with native-tls.)

**Comment by darind** [comment] 2023-09-29 13:04
Not sure about `native-tls`, but a simple curl on the command line works fine:

```
>curl --http1.1 -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" https://chat.openai.com -vp
```

**Comment by djc** [comment] 2023-09-29 13:07
curl has like 9 different TLS backends, so it really depends where you got your curl. `curl -V` should tell you more.

**Comment by darind** [comment] 2023-09-29 13:10
Tried on Windows (`schannel`):

```
curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
```

and on MacOS (I have a custom built curl here):

```
curl 7.85.0-DEV (x86_64-apple-darwin21.6.0) libcurl/7.85.0-DEV (SecureTransport) BoringSSL zlib/1.2.11 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.54.0 quiche/0.14.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets zstd
```

On Windows it works fine, on MacOS it returns 403. rustls example fails on both Windows and MacOS.

**Comment by djc** [comment] 2023-09-29 13:26
All this isn't really that relevant to the rustls maintainers. I just think that until you have a test that differs across a small number of factors (I'm still not sure what curl sends on the wire as a HTTP/1.1 request) it's not obvious why your first suspicion is that this is because of rustls -- even if it is, we have an issue for this already. Going to close this now.

**Closed by djc** 2023-09-29 13:26 UTC

**Comment by darind** [comment] 2023-09-29 13:29
Well, one example in which `rustls` differs from BringSSL on MacOS is that it doesn't send the Grease TLS extension, among other differences. This can be seen The differences can be seen quite well here: https://tls.peet.ws/api/all

**Comment by cpu** [comment] 2023-09-29 13:30
In general robust TLS fingerprint evasion is a cat and mouse game that, in my experience, requires significant investment. That investment is often at odds with the goals of a general purpose TLS library, which is why it's very common for censorship avoidance projects to fork a TLS library to customize the lowest levels of the handshake to avoid fingerprinting. E.g. see [this fork of the Go TLS library](https://pkg.go.dev/github.com/refraction-networking/utls). That project is [already discussing Rustls](https://github.com/refraction-networking/utls/issues/103).

**Comment by darind** [comment] 2023-09-29 13:33
Yeah, speaking about go-lang, I also found this https://github.com/CUCyber/ja3transport
