### ISSUE TITLE
Remove ring or make it as an optional dependency

### ISSUE THREAD

**Issue by axetroy** [rustls/rustls#1024] opened 2022-03-19 03:30 UTC
Ring depends on C and Assembly, it is hard to cross-compile.

And most of the Rust projects depend on Rustls, which makes most of the Rust projects can't cross-compile. 

> ---

Rust support cross-compile

But most of dependencies depends on Rustls that do not support cross-compile, so Rust does not support cross-compile

**Comment by djc** [comment] 2022-03-19 04:15
As far as I know, the ring project was already working on converting all the C to Rust. Now that Rust supports inline assembly, the raw assembly can probably also be removed from ring over time.

Dropping ring as a dependency from rustls seems very farfetched. There'd need to an alternative implementation of all the crypto primitives with similar security assertions, and I'm not convinced that exists today.

**Comment by ctz** [comment] 2022-03-27 08:21
Could you say what targets and architectures you are wanting to cross-compile rustls for that you currently cannot?

**Comment by sonder-joker** [comment] 2022-04-30 17:11
> Could you say what targets and architectures you are wanting to cross-compile rustls for that you currently cannot?

I've been working on crypto and tls support in wasm (wasm32-wasi) recently.
This repo have an issue https://github.com/rustls/rustls/issues/808 talking about webassembly support, however, crypto implementation in webassembly may cannot implement constant-time algorithms easily. https://github.com/WebAssembly/wasi-crypto/issues/21 talk about it, not only about constant-time, hardware crypto acceleration is also in consider. For many reasons, I think implement ring in wasm32-wasi not so ideal.
A possible solution is to provide a middle layer, I think add middle layer [defined by rust-crypto]( https://github.com/RustCrypto/traits ) can provide stronger compatibility. Rust-crypto provide a set of universal trait about crypto relative function. So we can just replace direct call ring by tls -> rust-crypto -> ring.
As wasm32-wasi side, we can just simple implement rust-crypto -> [wasi-crypto proposal interface](https://github.com/WebAssembly/wasi-crypto). wasi-crypto proposal have a preliminary implementation in [wasmtime](https://github.com/bytecodealliance/wasmtime/tree/main/crates/wasi-crypto) and [wasmedge](https://github.com/WasmEdge/WasmEdge/pull/1282).
However, I dont't know if this is easy enough to implement. If this solution can be considered, I would be glad to help implement the middle layer switch.

**Comment by quininer** [comment] 2022-05-01 02:31
This should be a duplicate of https://github.com/rustls/rustls/issues/521 and https://github.com/rustls/rustls/issues/390 .

**Comment by DemiMarie** [comment] 2022-05-04 21:58
> As far as I know, the ring project was already working on converting all the C to Rust. Now that Rust supports inline assembly, the raw assembly can probably also be removed from ring over time.
> 
> Dropping ring as a dependency from rustls seems very farfetched. There'd need to an alternative implementation of all the crypto primitives with similar security assertions, and I'm not convinced that exists today.

Does OpenSSL provide such assertions?  If not, the Linux kernel cryptographic API should.

**Comment by djc** [comment] 2022-05-05 19:06
Yeah, let's continue discussion on this in #521.

**Closed by djc** 2022-05-05 19:06 UTC
