### ISSUE TITLE
Using rustls for machine-to-machine w/ private CA and no DNS

### ISSUE THREAD

**Issue by jadamcrain** [rustls/rustls#331] opened 2020-01-05 17:40 UTC
I couldn't tell if this was possible from scanning the docs. All of the client examples appear to take a `DNSNameRef`.  Lots of m2m environments (e.g. industrial) don't use DNS at all in favor of static IP addresses, and therefore don't use DNS names as the CN or provide the `SubjectAlternativeName` extension at all.

Is it possible to use Rustls w/o the client performing hostname validation via the server CN and/or extensions?

I also have a requirement to parse a custom X.509 extension that contains authz info. Is this possible as well?

**Comment by briansmith** [comment] 2020-01-06 22:25
> therefore don't use DNS names as the CN or provide the `SubjectAlternativeName` extension at all.

What do these things use as an ID?

**Comment by jadamcrain** [comment] 2020-01-06 23:06
non-domain name `CN` or a list of allowed IP addresses in the `SAN` extension.

This example X.509 cert is from the Modbus TLS security standard. 

![client_cert](https://user-images.githubusercontent.com/305813/71855442-e6e13280-3095-11ea-9f50-209d88ab43fc.png)

**Comment by jadamcrain** [comment] 2020-05-23 20:58
Just checking in on this. Did #329 address this fully? Is there anything I can do in terms of a contribution to move this forward?

**Comment by sehz** [comment] 2020-06-03 02:05
I also like to move this forward

**Comment by jadamcrain** [comment] 2020-11-28 22:22
It appears like this might be possible since `0.18.0` release with the `dangerous()` configuration to set client/server verification not-based on Web-PKI.

1) It seems non-ideal (and extra dangerous) to make everyone bring their own x.509 parser for these applications. 

2) I've looked at `x509-signature` crate. I would like to see a more complete x.509 representation to work with. It appears like it doesn't fully parse a lot of things.

Just updating this ticket. I will do some playing around with `x509-signature` and our own x509 library to see which path we end up taking for our application.  We might end up contributing a more complete m2m/non-web verifier to the ecosystem.

**Comment by IniterWorker** [comment] 2022-02-04 14:46
Hi folks, 

The same need here,

Is there a way to workaround temporarily. I'd to use this crate for a project. But, I must comply with m2m without a DNS server.

I am struggling with "how to not provide a DNS Name server" when you are using the "dangerous" feature.

Any hints are welcome,

B. r

**Comment by Ralith** [comment] 2022-02-04 22:14
As a hacky work-around, you can make up whatever hostname you want, so long as what the client supplies to `connect` matches the certificate.

**Comment by jadamcrain** [comment] 2022-02-07 01:17
Update. We have this working for implementing the secure Modbus spec.  We use `webpki` for the heavy lifting of chain validation and for name validation.

After that pass we use another x.509 parser to extract the info from the custom extension:

https://github.com/stepfunc/rodbus/blob/main/rodbus/src/tcp/tls/server.rs#L163

In our case, we also needed to able to support certificates that do not have the SAN extensions but instead just use the CN for identity.
 
https://github.com/stepfunc/rodbus/blob/main/rodbus/src/tcp/tls/mod.rs#L105

It would be nice if more of these kind of options could be available in rustls/webpki in the future.  ATM, rustls is very tightly coupled to it's primary use case... https.

**Comment by bdaehlie** [comment] 2022-11-02 13:56
This issue seems to be able several different issues at once and it's not very clear what they are from the title or initial description.

Would be great if the reporter could report separate issues more clearly and close out this ticket.

**Comment by nyurik** [comment] 2022-11-03 13:38
I keep seeing workarounds like [this one](https://github.com/awslabs/aws-sdk-rust/discussions/650) (AWS labs by @azzamsa) to essentially disable all cert validation for edge cases. Would it make sense to perhaps add a dummy noop `NoCertificateVerification` to the `dangerous` mod?   It is already dangerous, so I think it makes sense to make the life of all those who need it simpler - rather than we all do a lot of boilerplate copy/paste.   Thanks!!

**Comment by djc** [comment] 2022-11-03 13:56
Personally I'm comfortable with making the stupidly insecure cases hard to implement -- and I don't think the boilerplate is all that bad (just like 10 lines that you can readily copy/paste). The issue you reference also has no rationale for disabling verification. IMO a somewhat important point is that rustls should work fine with a private CA without DNS (you can pass the server name manually). What doesn't work currently is certificates with IP addresses instead of server names in SAN, see #184 (to be fixed in https://github.com/rustls/webpki/pull/5).

I don't see why we should support self-signed certificates when you can readily do a private CA setup.

Perhaps we should make it easier to access the server's certificate after authentication but it seems somewhat reasonable to me to not parse since most users by far wouldn't need it.

**Comment by nyurik** [comment] 2022-11-03 14:27
@djc 10 lines of code, if required by a significant number of developers, should be included because 1) they will be properly documented and 2) can be modified in a central place.  This of course assumes that it is indeed needed (not yet unconfirmed).

Yet, my bigger concern is the ease of switching from openssl. If want to help rustls adaption, it should be as painless as possible to switch over. For example, Martin project had to do this [fairly involved](https://github.com/maplibre/martin/pull/474/files#diff-2447a883717d9b70aaf45972bd6124a9df2449ae0276673b4e5a9835435670ac) conversion code -- and my biggest concern is that I actually do NOT know if this is a correct way to do it or not -- and that's why I think it is important to have the same feature in rustls.

```rust
// openssl
if danger_accept_invalid_certs {
    builder.set_verify(SslVerifyMode::NONE);
```
vs 
```rust
/// rustls
struct NoCertificateVerification {}

impl rustls::client::ServerCertVerifier for NoCertificateVerification {
    fn verify_server_cert(
        &self,
        _end_entity: &rustls::Certificate,
        _intermediates: &[rustls::Certificate],
        _server_name: &rustls::ServerName,
        _scts: &mut dyn Iterator<Item = &[u8]>,
        _ocsp: &[u8],
        _now: std::time::SystemTime,
    ) -> Result<rustls::client::ServerCertVerified, rustls::Error> {
        Ok(rustls::client::ServerCertVerified::assertion())
    }
}

if danger_accept_invalid_certs {
    builder
        .dangerous()
        .set_certificate_verifier(Arc::new(NoCertificateVerification {}));
}
```

**Comment by nyurik** [comment] 2022-11-03 16:41
P.S. I created a new #1124 to document the migration path from openssl to rustls, e.g. as a wiki page? This could also result in a clearer understanding of what openssl APIs could be ported over for the ease of migration.

**Comment by jadamcrain** [comment] 2022-11-03 16:49
> I don't see why we should support self-signed certificates when you can readily do a private CA setup.

@djc Because some systems already work in a certain way and it is not within our power to change the way in which the owners of these systems run them. PKI in industrial controls gets locked into a certain way of doing things and then doesn't have the flexibility to change. 

This is the same reason why we've had to do a complicated workaround for supporting certs that only have the `CN` and don't use the SAN extension. Our customers are using our DNP3 library (which uses rustls internally for TLS) to talk to CAISO:

https://www.caiso.com/Pages/default.aspx

The CAISO PKI prescribes the usage of CN and doesn't use SAN. The isn't a web use case so it's perfectly reasonable for them to not embed the SAN extension in their certs.

We've been able to work around these issues using `dangerous` but its less than ideal.

**Comment by cpu** [comment] 2023-03-31 16:59
With Rustls 0.21.0 there is now support for IP address subjects in certificates. I think we should close this issue and if there are remaining gaps it would be best to articulate them in more narrowly scoped issues. I think this issue has combined a few concerns and we'd have better luck finding a path forward for what remains with more targeted discussion in separate tickets.

**Closed by cpu** 2023-03-31 16:59 UTC

**Comment by jadamcrain** [comment] 2023-03-31 17:00
Agreed. Thank you.
