### ISSUE TITLE
No common ciphersuit when FFDHE and ECDHE ciphersuites are available on server and client using TLS 1.2

### ISSUE THREAD

**Issue by Taowyoo** [rustls/rustls#1860] opened 2024-03-20 01:02 UTC
# Bug description
When FFDHE and ECDHE ciphersuites are available on server and client when common version is TLS 1.2. Server will fail to choose common ciphersuite.

See:
https://github.com/rustls/rustls/blob/fb67f0145608c995241b852c68ed7ce28b1c241e/rustls/src/server/hs.rs#L479-L482

It is obvious that no suite cannot support DHE and ECDHE KeyExchangeAlgorithm at same time when `ecdhe_possible` and `ffdhe_possible` are true.

# Need backport

versions:
- 0.23

**Comment by Taowyoo** [comment] 2024-03-20 01:06
Created PR for fixing this: https://github.com/rustls/rustls/pull/1861

Notice, you could produce the error by revertting the fix code in `src` and run
```
cargo test --test api_ffdhe server_avoids_cipher_suite_with_no_common_kx_groups
```

**Comment by djc** [comment] 2024-03-20 10:27
Is this a regression from #1784, or has this been broken since the introduction of FFDHE support?

**Comment by Taowyoo** [comment] 2024-03-20 16:08
After testing, it's a regression from https://github.com/rustls/rustls/pull/1784.
My testing branch:
- https://github.com/fortanix/rustls/tree/yx/test-dhe
- https://github.com/fortanix/rustls/tree/yx/test-dhe-after-1784

**Comment by ctz** [comment] 2024-03-21 08:51
https://crates.io/crates/rustls/0.23.3 was released yesterday containing the fix for this.

**Closed by ctz** 2024-03-21 08:51 UTC
