### ISSUE TITLE
Can't send request to 1.1.1.1

### ISSUE THREAD

**Issue by kpcyrd** [rustls/rustls#281] opened 2019-07-26 03:09 UTC
I've noticed there's a way to disable sni, but there's no way to setup a ClientSession without a DNSNameRef. The problem is that webpki rejects plain ip addresses. This means I currently can't create a connection to https://1.1.1.1/

```
% target/debug/examples/tlsclient 1.1.1.1   
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidDNSNameError', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I think a possible workaround would be a default DNSNameRef like `invalid.com` and setting enable_sni to false, but I'd love to have a proper solution in rustls. :)

**Comment by Darkspirit** [comment] 2019-07-26 09:13
> The problem is that webpki rejects plain ip addresses. 

That's briansmith/webpki#54.

> This means I currently can't create a connection to https://1.1.1.1/

It doesn't even work via IPv6! :P

Alternative SANs:
https://cloudflare-dns.com/
https://one.one.one.one/

**Comment by ihciah** [comment] 2020-10-14 03:20
I encountered the problem too... 
After reviewing the code of rustls I think the root cause is the unconsideration of the possibilty of ip matching. It tries converting host name to dns name, which can not be ip. However, host name can be ip and matching ip fields in certificates.

**Comment by djc** [comment] 2020-10-14 07:32
This seems like a duplicate of #184.

**Comment by jbg** [comment] 2021-12-29 13:52
> This seems like a duplicate of #184.

It is — I think this can be closed?

**Closed** 2021-12-29 14:00 UTC
