### ISSUE TITLE
Support for ESP-IDF?

### ISSUE THREAD

**Issue by stevefan1999-personal** [rustls/rustls#1400] opened 2023-08-15 10:20 UTC
esp-idf have std target, and with a recent patch in tokio I was able to run Hyper onto it. The only thing left to make it fully rustify is getting TLS support.

**Comment by djc** [comment] 2023-08-15 10:58
What problem are you running into? rustls itself doesn't contain any platform-specific code, and if the problem is with ring we are limited in our options (though see #521 for a potential workaround).

**Comment by cpu** [comment] 2023-08-29 13:47
Closing this since there's not enough information to be actionable. I recommend following #521 for options to enable broader platform support.

Thanks!

**Closed by cpu** 2023-08-29 13:47 UTC
