### ISSUE TITLE
When we do a large concurrency test, the error "dec_key.open_within ring::error::Unspecified"   happens  occasionally

### ISSUE THREAD

**Issue by lidong14** [rustls/rustls#391] opened 2020-08-04 12:14 UTC
we test the version 0.17 and 0.18, it happens always
the detailed error below:
ERROR []server forward found error: Custom { kind: ConnectionAborted, error: hyper::Error(Connect, Custom { kind: InvalidData, error: DecryptError }) }

we add log in rustls.
rustls-debug- verify_slices_are_equal1111. 16 - 16 a= [158, 236, 118, 133, 29, 17, 52, 225, 156, 160, 198, 125, 53, 3, 8, 250] , b =[33, 24, 195, 72, 198, 238, 162, 0, 43, 94, 191, 49, 20, 217, 202, 7]
rustls-debug- nstant_time::verify_slices_are_equa
rustls-debug- dec_key.open_within ring::error::Unspecified
rustls-debug- verify_slices_are_equal1111. 16 - 16 a= [10, 166, 13, 85, 11, 83, 41, 231, 192, 214, 68, 54, 146, 89, 9, 30] , b =[170, 113, 80, 238, 59, 179, 126, 246, 220, 118, 64, 28, 30, 45, 154, 152]
rustls-debug- nstant_time::verify_slices_are_equa
rustls-debug- dec_key.open_within ring::error::Unspecified
connect_tls failure, Ok(V4(127.0.0.1:XXXX)),Custom { kind: InvalidData, error: DecryptError }
ERROR connect 127.0.0.1:XXXX error cannot decrypt peer's message
connect_tls failure, Ok(V4(127.0.0.1:XXXX)),Custom { kind: InvalidData, error: DecryptError }
ERROR connect 127.0.0.1:XXXX error cannot decrypt peer's message

**Comment by lidong14** [comment] 2020-08-04 12:23
![aa](https://user-images.githubusercontent.com/28534788/89293369-6799f880-d690-11ea-8f3c-6353945f5a6d.png)

**Comment by briansmith** [comment] 2020-08-04 17:27
Which target?

**Comment by lidong14** [comment] 2020-08-05 03:16
@briansmith the target is nginx service which version is 1.17.9. when we use the test service which use rustls ,  it doesnot hanppen 。

**Comment by silence-coding** [comment] 2020-08-05 07:36
I also had this error. According to the network packet capture, I found that the problem may occur in session reuse. When enable_tickets is set to false, this problem does not appear, but the throughput of the request also drops by half。

**Comment by ctz** [comment] 2020-10-11 11:33
Could you write precise reproduction steps for this? And preferably a pcap of it happening with a matching SSLKEYLOG?

**Comment by djc** [comment] 2022-06-24 10:07
Could you provide us with a minimal reproduction?

**Comment by DoumanAsh** [comment] 2022-06-24 10:17
Well, I'll try to create, but so far error makes no sense to me so I'm not sure what exactly causes error.
In first place it shouldn't be dependent on concurrency and the same code works just fine with openssl.
If I'll be able to create server that can simulate the same concurrent error I'll let you know.

I also tested latest rustls, but bug is still present there.

I have suspicion it is related to certificate, because in past the same code worked quite fine regardless of concurrency.

**Comment by DoumanAsh** [comment] 2022-06-25 04:44
Small clarification
It seems my case is a bit different as rustls fails with different reasons.
For example it sends `BadRecordMac` in few tests
I doubt this is in particularly server fault as openssl seems to work fine, which means it is likely either network issues (which would be weird to happen only with rustls implementation) or rustls code doing something weird

I'm trying to see if I encounter such error when trying to perform http requests on servers other than my company's one

**Comment by DoumanAsh** [comment] 2022-08-11 06:29
I'm sorry I no longer able reproduce this issue, not even with previous cases where I had 100% reproduction

**Comment by djc** [comment] 2022-08-11 12:34
Okay, I guess we'll just close this since there's no way to make progress on a diagnosis.

**Closed by djc** 2022-08-11 12:34 UTC
